### ISSUE TITLE
http://www.snmpsharpnet.com/ down?

### ISSUE THREAD

**Issue by eulus** [rqx110/SnmpSharpNet#20]
the link http://www.snmpsharpnet.com/ is routed to http://www.snmpsharpnet.com/cgi-sys/suspendedpage.cgi

Now theres no help for your package :-(

**Comment by rqx110** [comment]
you can visit https://github.com/rqx110/SnmpSharpNet/wiki to get help

**Comment by dylan666** [comment]
If this repo and the NuGet package are not maintained by the original developer this should be clarified in [README.md](https://github.com/rqx110/SnmpSharpNet#readme) where the official site is linked without further information

**Comment by lextm** [comment]
@dylan666 probably because [the history is bit of tough](https://docs.lextudio.com/blog/history-of-snmpsharpnet/).

@rqx110 Your Wiki page still has several links to the old domain, but that domain name is lost to wrong hands. You'd better remove such links in case they later link to whatever contents out of your control.

**Comment by dylan666** [comment]
Thank you for the explanation!

**Comment by rqx110** [comment]
Thanks @lextm. And I have removed all the link of snmpsharpnet.com
